name: neiu-data-science-workshop-2025-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mystmd
  - cookiecutter
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - jupyterlab
  - pythia-datasets
  - imbalanced-learn
  - pip
  - pip:
    - sage-data-client
